version: 2.1
jobs:
  create_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["57:37:dd:57:2f:04:b9:f5:24:8f:a3:6d:5e:94:4a:92"]
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
      - run:
          name: Configure server
          command: |
          ansible-playbook -i inventory.txt template.yml

workflows:
  welcome:
    jobs:
      - create_infrastructure
